### ISSUE TITLE
Validate Existing DTD

### ISSUE THREAD

**Issue by MatthD** [bathos/hardcore-xml#2]
Hello,

I am not sure if your Node program could be used to validate XML files with already written specific DTD's files as xmlstarlet could do ? isn't it ?

Regards

**Comment by bathos** [comment]
Hey MatthD. I’m pretty sure I don’t understand the question. When a doctype declaration that refers to an external DTD is encountered, the dereferencing function is called to retrieve the (presumably already written?) DTD:

https://github.com/bathos/hardcore-xml#optsdereference
